### ISSUE TITLE
test_Hog_OrderedSender stalled on NixOs

### ISSUE THREAD

**Issue by smunix** [Morgan-Stanley/hobbes#378]
```gdb
#0  0x00007ffff7ac41f3 in clock_nanosleep@GLIBC_2.2.5 () from target:/nix/store/rqrklqsvw4ydpcg5kdcvn506fhcbqxk2-glibc-2.32-10/lib/libc.so.6
#1  0x00007ffff7ac9163 in nanosleep () from target:/nix/store/rqrklqsvw4ydpcg5kdcvn506fhcbqxk2-glibc-2.32-10/lib/libc.so.6
#2  0x00007ffff7ac90aa in sleep () from target:/nix/store/rqrklqsvw4ydpcg5kdcvn506fhcbqxk2-glibc-2.32-10/lib/libc.so.6
#3  0x00000000004ebf8b in HogApp::waitSegFileCount(std::function<bool (int)>) ()
#4  0x00000000004e7807 in test_Hog_OrderedSender() ()
#5  0x0000000000542c3d in TestCoord::runTestGroups(Args const&) ()
#6  0x000000000048b345 in main ()
```

**Comment by smunix** [comment]
dup #329
